name: Deploying

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run the lint sctipt
        run: npm run lint

  deploy:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Set git config
        run: |
          git config --global user.email "${{env.GITHUB_ACTOR}}"
          git config --global user.name "${{env.GITHUB_ACTOR}}"

      - name: Run the deploy sctipt
        run: npm run deploy
