name: Linting

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Run the lint sctipt
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
